$font = Comic Code Ligatures

general {
    hide_cursor = false
}

animations {
    enabled = false
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 30
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 2
    inner_color = rgba(3b4252ff)

    outer_color = rgba(e5e9f0ff) rgba(81a1c1ff)  90deg
    check_color = rgba(e5e9f0ff) rgba(b48eadff)  90deg
    fail_color  = rgba(e5e9f0ff) rgba(bf616aff)  90deg

    font_color = rgba(E7ECF4ff)
    fade_on_empty = false
    rounding = 10

    font_family = $font
    placeholder_text =
    fail_text = $PAMFAIL$FPRINTFAIL

    dots_spacing = 0.3

    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] cowsay $(fortune)
    font_size = 10
    font_family = $font
    color = rgba(e5e9f0ff)

    position = -100, 20
    halign = right
    valign = bottom
}

